version: "2.3"
services:
  web:
    build: .
    ports:
      - 9001:9001
    depends_on:
      - mongo
    labels:
      - "traefik.enable=true"
      - "traefik.port=9001"
      - "traefik.frontend.rule=Host:testing.yuksinau.id"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27020:27017