version: "2.3"
services:
  web:
    image: ujiservice
    ports:
      - 9001:9001
    depends_on:
      - mongo
    labels:
      - "traefik.frontend.rule=Host:api-uji.yuksinau.id"

  mongo:
    image: mongo
    restart: always
    ports:
      - 27020:27017